public class Notification implements Cloneable {
    public static final byte AUTOMATION_MODEL_AUTO_PARAM = 4;
    public static final byte AUTOMATION_MODEL_CYCLE = 3;
    public static final byte AUTOMATION_MODEL_OFF = 2;
    public static final byte AUTOMATION_MODEL_ON = 1;
    public static final byte AUTOMATION_MODEL_VPD = 6;
    public static final byte AUTOMATION_MODEL_VPD_PARAM = 5;
    public boolean advActive;
    public String advId;
    public byte autoSetModel;
    public byte beeps;
    public byte childId;
    public byte childIndex;
    public int codeAddress;
    public char cycleOff;
    public char cycleOn;
    public byte day;
    public String devCode;
    public String devId;
    public char end;
    public byte gearBuffHum;
    public byte gearBuffTmpF;
    public byte gearBuffVpd;
    public byte gearSetModel;
    public byte gearTransHum;
    public byte gearTransTmpF;
    public byte gearTransVpd;
    public byte groupIndex;
    public byte hHum;
    public byte hTmpC;
    public byte hTmpF;
    public byte hVpd;
    public int id;
    public byte lHum;
    public byte lTmpC;
    public byte lTmpF;
    public byte lVpd;
    public int levelOff;
    public int levelOn;
    public String mac;
    public byte model;
    public String name;
    public int nameCode;
    public boolean open;
    public byte port;
    public byte portInfo;
    public byte portStatus;
    public byte portType;
    public char start;
    public byte switchBuffHum;
    public byte switchBuffTmpF;
    public byte switchBuffVpd;
    public byte tHum;
    public byte tTmpC;
    public byte tTmpF;
    public byte tVpd;
    public char timeDuration;
    public char timeEnable;
    public byte tmpHum;
    public byte type;
    public byte vpdTmpHum;
}